/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/myPage` | `/myPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/personalTraining` | `/personalTraining`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reservation` | `/reservation`; params?: Router.UnknownInputParams; } | { pathname: `/lib/definition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/court-room/[id]` | `/court-room/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/myPage` | `/myPage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/personalTraining` | `/personalTraining`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reservation` | `/reservation`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/definition`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/court-room/[id]` | `/court-room/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/sign-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/myPage${`?${string}` | `#${string}` | ''}` | `/myPage${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/personalTraining${`?${string}` | `#${string}` | ''}` | `/personalTraining${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/reservation${`?${string}` | `#${string}` | ''}` | `/reservation${`?${string}` | `#${string}` | ''}` | `/lib/definition${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/myPage` | `/myPage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/personalTraining` | `/personalTraining`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reservation` | `/reservation`; params?: Router.UnknownInputParams; } | { pathname: `/lib/definition`; params?: Router.UnknownInputParams; } | `${'/(app)'}/court-room/${Router.SingleRoutePart<T>}` | `/court-room/${Router.SingleRoutePart<T>}` | { pathname: `${'/(app)'}/court-room/[id]` | `/court-room/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
